repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=600']

-   repo: https://github.com/ambv/black
    rev: 24.8.0
    hooks:
      - id: black

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.6.2"
    hooks:
      - id: ruff
        args: [--fix, --show-fixes, --show-files]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        args: [--install-types, --non-interactive]
        exclude: examples|docs

-   repo: https://github.com/DanielNoord/pydocstringformatter
    rev: v0.7.3
    hooks:
      - id: pydocstringformatter
        args:
        - --no-final-period
        - --no-split-summary-body
