from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class Numeric(Protocol):
    def __add__(self, *args: Any, **kwargs: Any) -> Any: ...

    def conjugate(self, *args: Any, **kwargs: Any) -> Any: ...

    def real(self, *args: Any, **kwargs: Any) -> Any: ...

    def imag(self, *args: Any, **kwargs: Any) -> Any: ...

    def __eq__(self, *args: Any, **kwargs: Any) -> Any: ...

    def __mul__(self, *args: Any, **kwargs: Any) -> Any: ...

    def __ne__(self, *args: Any, **kwargs: Any) -> Any: ...

    def __sub__(self, *args: Any, **kwargs: Any) -> Any: ...

    def __truediv__(self, *args: Any, **kwargs: Any) -> Any: ...
